image:
  name: traefik
  tag: "2.5.4"

providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true

additionalArguments:
  - "--certificatesresolvers.le-staging.acme.tlschallenge=true"
  - "--certificatesresolvers.le-staging.acme.email=<replace-me>"
  - "--certificatesresolvers.le-staging.acme.storage=/data/acme.json"
  - "--certificatesresolvers.le-staging.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
  - "--certificatesresolvers.le.acme.tlschallenge=true"
  - "--certificatesresolvers.le.acme.email=<replace-me>"
  - "--certificatesresolvers.le.acme.storage=/data/acme.json"
  - "--log.level=DEBUG"
  - "--providers.file.filename=/config/dynamic.yaml"

ingressClass:
  enabled: true

deployment:
  initContainers:
    - name: volume-permissions
      image: busybox:1.31.1
      command: ["sh", "-c", "chmod -Rv 600 /data/*"]
      volumeMounts:
        - name: data
          mountPath: /data

persistence:
  enabled: true
  name: data
  accessMode: ReadWriteOnce
  size: 128Mi
  path: /data    

volumes:
  - name: '{{ printf "%s-configs" .Release.Name }}'
    mountPath: "/config"
    type: configMap

